environment            = "prd"
prefix                 = "aks-demo"
location               = "uksouth"
provision_blob_storage = "true"
provision              = "true"
acrname                = "aksdemoprdacr"
